### ISSUE TITLE
Support multiple databases

### ISSUE THREAD

**Issue by rabbiveesh** [BemiHQ/BemiDB#11]
From the looks of the README, the `bemidb` binary will only serve one database - is it in the works to allow it to serve more than one, acting more like a PG cluster? Matters to me b/c we do database-per-tenant isolation + would be nice to use this

**Comment by exAspArk** [comment]
Hey @rabbiveesh — thanks for submitting this issue!

We'll add support for multiple databases, so it's possible to use the same `bemidb` binary for separate reads and writes.

For example:

* Sync PG1 into the shared Iceberg
  * `./bemidb --pg-database-url [PG1_URL] --iceberg-path iceberg --iceberg-catalog pg1 sync`
* Sync PG2 into the shared Iceberg
  * `./bemidb --pg-database-url [PG2_URL] --iceberg-path iceberg --iceberg-catalog pg2 sync`
* Read from the shared Iceberg
  * `./bemidb --iceberg-path iceberg start`

**Comment by exAspArk** [comment]
We decided to keep things simple for now and allow syncing multiple PostgreSQL databases into the same BemiDB databases by using schema prefixes like:

```sh
./bemidb --pg-schema-prefix db1_ ... sync
./bemidb --pg-schema-prefix db2_ ... sync

./bemidb start
psql postgres://localhost:54321/bemidb -c \
  "SELECT * FROM db1_public.[TABLE] JOIN db2_public.[TABLE] ON ..."
```

You can find more information here https://github.com/BemiHQ/BemiDB#syncing-from-multiple-postgres-databases
