### ISSUE TITLE
 Unsupported PostgreSQL type: xid8

### ISSUE THREAD

**Issue by wub** [BemiHQ/BemiDB#13]
Hello, It would be great if `xid` (`int32`?) and `xid8` (`int64`?) types were supported. Thanks!

**Comment by exAspArk** [comment]
Hey @wub — thanks for submitting this issue!

This should be fixed now (converted to unsigned ints). Would you be able to [install](https://github.com/BemiHQ/BemiDB#quickstart) the latest version and try again?

Let us know if you hit any other issues.
