### ISSUE TITLE
Panic on PostgreSQL _ltree Type During Sync Operation

### ISSUE THREAD

**Issue by divin-kp** [BemiHQ/BemiDB#17]
When running a sync operation with BemiDB, the process fails with a panic due to encountering PostgreSQL's ltree type. While PostgreSQL supports ltree for hierarchical data structures, there appears to be no current mapping to ltree type in the sync operation. So the command end with below error message,

`panic: Unsupported PostgreSQL type: _ltree`

Steps done:

  1.   Install BemiDB using the following command.
  `curl -sSL https://raw.githubusercontent.com/BemiHQ/BemiDB/refs/heads/main/scripts/install.sh | bash`

  2.   Try to sync a PostgreSQL database (version 13.x) using:
   `./bemidb --pg-database-url postgres://<user>:<password>@<host>:<port>/<dbname> sync`
    
Kindly check and let me know why this issue has occurred so that I can continue with my evaluation.

**Comment by exAspArk** [comment]
Hi @divin-kp — thank you for submitting this issue!

We've added basic support for `ltree` data type by representing it as a string. Would you be able to download the [latest version](https://github.com/BemiHQ/BemiDB#quickstart) and try again?

**Comment by divin-kp** [comment]
**Thank you for the solution!**
The issue with "ltree" has been successfully resolved as per your guidance. I appreciate your prompt assistance.  Thanks again for your help!
