### ISSUE TITLE
I encountered a panic error when using the PostgreSQL type `_semver`. The error message is as follows:

### ISSUE THREAD

**Issue by salilsaifuddin** [BemiHQ/BemiDB#20]
### Steps to Reproduce
1. Install the `semver` extension.
2. Attempt to use the `_semver` type in a query or table definition.
3. Observe the panic error.

### Expected Behavior
The `_semver` type should be supported without causing a panic.

### Actual Behavior
The application panics with the error message: `Unsupported PostgreSQL type: _semver`.

Please provide a list of all supported extensions by this tool.

**Comment by exAspArk** [comment]
Hi @salilsaifuddin — thank you for submitting this issue!

This should be fixed in `v0.17.1`. Would you be able to download the [latest version](https://github.com/BemiHQ/BemiDB#quickstart) and try again?
