### ISSUE TITLE
Support for select which tables to sync

### ISSUE THREAD

**Issue by DimShadoWWW** [BemiHQ/BemiDB#22]
BemiDB is awesome, but I would like to be able to select which tables to sync instead of downloading all tables.

Do you have any suggestions/plans for this?

Thanks

**Comment by exAspArk** [comment]
Hi @DimShadoWWW — thank you for submitting this issue. Yes, we plan to build this functionality this week!

**Comment by arjunlol** [comment]
Hi @DimShadoWWW, we've added support for selecting which tables to sync. You can test using the `include-tables` or `exclude-tables` arguments: 
```
./bemidb --include-tables schema.table1,public.users 
./bemidb --exclude-tables schema.table3,public.cache
```

You can find more information here https://github.com/BemiHQ/BemiDB#syncing-from-selective-tables.

Hopefully this works for you. Let us know!

**Comment by arjunlol** [comment]
FYI @DimShadoWWW these flags were renamed to `pg-include-tables` and `pg-exclude-tables` in the latest release.
