### ISSUE TITLE
Querying not working

### ISSUE THREAD

**Issue by ariebombarie14** [BemiHQ/BemiDB#23]
Importing of data works, then running 'SELECT * FROM information_schema.tables' shows the tables.
But after that i only get internal error, from the debug logs i see: Table with 'namexx' does not exist.
I follow your doc and use 'SELECT COUNT(*) FROM [table_name]'.
I tried many options like for example:
SELECT COUNT(*) FROM test_table
SELECT COUNT(*) FROM test_table_q1
SELECT COUNT(*) FROM public.test_table
SELECT COUNT(*) FROM public.test_table_q1
And some select queries with data from my own database.
What am i doing wrong?

**Comment by ariebombarie14** [comment]
I figured it out, you can't run bemidb and then import/sync data.
Have to import/sync data first before starting bemidb.

**Comment by exAspArk** [comment]
Hi @ariebombarie14 — awesome, thanks for the update!

We're going to close this issue. Let us know if you have any other questions
