### ISSUE TITLE
Sync Failed with `timestamptz` Parsing Error

### ISSUE THREAD

**Issue by pradeepcdlm** [BemiHQ/BemiDB#26]
The sync process failed while handling a table containing a `timestamptz` type column. The error log shows the following message:

`panic: parsing time "2023-04-11 09:38:46.093381+05:30": extra text: ":30"`

It appears that the timestamp format is not being parsed correctly, specifically for time zones with fractional seconds or offsets.

**Steps to Reproduce**
1. Attempt to sync a table that includes a column of type `timestamptz`.
2. Ensure the column contains values with time zones in the format +HH:MM (use a value similar to the one used in the error message).
3. Observe the sync failure with the error mentioned.

**Expected Behavior**
The sync process should correctly handle and parse `timestamptz` columns, regardless of the time zone format.

**Actual Behavior**
The sync process fails with a panic error due to parsing issues in the `timestamptz` column.

I request your attention to this issue and would appreciate it if you could resolve it at the earliest convenience.

**Comment by arjunlol** [comment]
Hey @pradeepcdlm — thanks for submitting such a detailed issue description!

This should be resolved now in the latest release. Would you be able to [install](https://github.com/BemiHQ/BemiDB#quickstart) the latest v0.16.1 version and try again?

**Comment by pradeepcdlm** [comment]
Thank you, @arjunlol , for your prompt assistance. I'll test out the latest version.
