### ISSUE TITLE
panic: Unsupported PostgreSQL type: bit

### ISSUE THREAD

**Issue by divin-kp** [BemiHQ/BemiDB#28]
The sync process failed while handling a table containing a column of type bit. The error log shows the following message:

`panic: Unsupported PostgreSQL type: bit`

It appears that the sync process does not support the bit data type in PostgreSQL, leading to a panic and termination of the operation.

**Steps to Reproduce:**

1. Attempt to sync a table that includes a column of type bit.
2. Ensure the column contains valid values for the bit data type.
3. Observe the sync failure with the error mentioned.

**Expected Behavior:** 
The sync process should handle columns of type bit without errors.

**Actual Behavior:** 
The sync process fails with a panic error when encountering a column of type bit.

I request your attention to this issue and would appreciate it if you could resolve it at the earliest convenience.

**Comment by exAspArk** [comment]
Hi @divin-kp — thank you for submitting this issue! 🙌 

We've added support for `bit` column types in v0.20.0. Would you be able to download the [latest version](https://github.com/BemiHQ/BemiDB#quickstart) and try again?

**Comment by divin-kp** [comment]
Thank you for the update and adding support for `bit `column types in v0.20.0! I’ve tested the latest version, and the sync process is now working perfectly. Appreciate your prompt resolution of the issue!
