### ISSUE TITLE
panic: Unsupported PostgreSQL type: xml

### ISSUE THREAD

**Issue by divin-kp** [BemiHQ/BemiDB#29]
The sync process failed while handling a table containing a column of type xml. The error log shows the following message:

`panic: Unsupported PostgreSQL type: xml
`

It appears that the sync process does not support the xml data type in PostgreSQL, leading to a panic and termination of the operation.

Additionally, we are using some uncommon PostgreSQL data types apart from standard ones like **int8, json, and bpchar**. Please ensure that these unusual data types are also supported during the sync process.

**Steps to Reproduce:**

Attempt to sync a table that includes a column of type xml.
Ensure the column contains valid values for the xml data type.
Observe the sync failure with the error mentioned.

**Expected Behavior:**
The sync process should handle columns of type xml without errors.

**Actual Behavior:**
The sync process fails with a panic error when encountering a column of type xml.

**Request:**
I request your attention to this issue and would appreciate it if you could resolve it at the earliest convenience.

**Comment by exAspArk** [comment]
Hi @divin-kp — thank you for submitting this issue!

We've added support for XML column types in v0.27.0. Would you be able to download the [latest version](https://github.com/BemiHQ/BemiDB#quickstart) and try again?

> we are using some uncommon PostgreSQL data types apart from standard ones like int8, json, and bpchar

These should be supported. You can find the full list of supported PostgresSQL data types in [this table](https://github.com/BemiHQ/BemiDB#data-type-mapping). Please let us know if you encounter any issues.

**Comment by divin-kp** [comment]
Thank you for the update! I’ll download the latest version and test the changes for XML column type support.

Additionally, I’ll review the full list of supported PostgreSQL data types and verify compatibility with the uncommon types we are using. If I encounter any further issues, I’ll be sure to update you.

Thanks again for your prompt response and support!
