### ISSUE TITLE
Panic on Sync on macos Apple Silicon

### ISSUE THREAD

**Issue by meetmauro** [BemiHQ/BemiDB#3]
hi all,
after installation I did:

./bemidb --pg-database-url postgres://postgres:@localhost:5432/merc sync

but it failed:

2024/11/08 12:03:58 [INFO] Syncing partitions.m_targets_20240101...
panic: mkdir /Users/exaspark: permission denied

goroutine 1 [running]:
main.PanicIfError({0x104b5a6a0?, 0x1400040b260?}, {0x0?, 0x14000486000?, 0x104b5a6a0?})
	/Users/exaspark/Documents/Code/BemiHQ/BemiDB/src/utils.go:14 +0x9c
main.(*StorageLocal).CreateDataDir(0x0?, {{0x140003eeff0?, 0x0?}, {0x14000486000?, 0x140000f7a98?}})
	/Users/exaspark/Documents/Code/BemiHQ/BemiDB/src/storage_local.go:74 +0x78
main.(*IcebergWriter).Write(0x1400000e570, {{0x140003eeff0?, 0x140003eeff0?}, {0x14000486000?, 0x14000486000?}}, {0x14000494488, 0x5, 0x8}, 0x1400049c060)
	/Users/exaspark/Documents/Code/BemiHQ/BemiDB/src/iceberg_writer.go:336 +0x94
main.(*Syncer).syncFromPgTable(0x1400000e5a0, 0x14000413560, {{0x140003eeff0?, 0xa?}, {0x14000486000?, 0x0?}})
	/Users/exaspark/Documents/Code/BemiHQ/BemiDB/src/syncer.go:108 +0x304
main.(*Syncer).SyncFromPostgres(0x1400000e5a0)
	/Users/exaspark/Documents/Code/BemiHQ/BemiDB/src/syncer.go:46 +0x1a8
main.syncFromPg(0x1051e7580)
	/Users/exaspark/Documents/Code/BemiHQ/BemiDB/src/main.go:60 +0x24
main.main()
	/Users/exaspark/Documents/Code/BemiHQ/BemiDB/src/main.go:25 +0xb0

thanks

**Comment by exAspArk** [comment]
Hey @meetmauro! Would you be able to try again by using the latest version?

I've released this fix https://github.com/BemiHQ/BemiDB/commit/fac7bf5f55643a4c87f85992b974cf6ab80adbe7 in v0.2.0

**Comment by exAspArk** [comment]
Please let us know if this is still an issue after [installing](https://github.com/BemiHQ/BemiDB#quickstart) the latest version, and we'll reopen this issue
