### ISSUE TITLE
Server crashes when executing SELECT * FROM test('val');

### ISSUE THREAD

**Issue by Gudwlin** [BemiHQ/BemiDB#30]
**Describe the bug**
Server crashes when executing the following psql command

**What data setup do we need to do?**
BemiDB(main) with PostgreSQL (REL_16_STABLE).

**What is the necessary configuration info needed?**
My PostgreSQL configuration:
```
./configure 
```

**What is the command that caused the error?**
```
CREATE OR REPLACE FUNCTION test(val integer)
RETURNS integer AS $$
BEGIN
    RETURN val + 10;
END;
$$ LANGUAGE plpgsql;
```
```
psql postgres://localhost:54321/bemidb -c "SELECT * FROM test('val');"
```
backtrace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x100d78d]

goroutine 11 [running]:
main.(*SelectRemapper).remapTableFunction(0xc000133a40?, 0xc000422400)
	/app/select_remapper.go:258 +0xcd
main.(*SelectRemapper).remapSelectStatement(0xc000133a40, 0xc00041e060?, 0x0)
	/app/select_remapper.go:105 +0x4d9
main.(*SelectRemapper).RemapQueryTreeWithSelect(0xc000396140?, 0xc000420000)
	/app/select_remapper.go:47 +0x56
main.(*QueryHandler).remapQuery(0xc000133a60, {0xc000396140, 0x1a})
	/app/query_handler.go:381 +0x1a8
main.(*QueryHandler).HandleQuery(0xc000133a60, {0xc000396140, 0x1a})
	/app/query_handler.go:174 +0x65
main.(*Postgres).handleSimpleQuery(0xc0001122a0, 0xc000133a60, 0xc0000e8b00)
	/app/postgres.go:95 +0xb6
main.(*Postgres).Run(0xc0001122a0, 0xc000133a60)
	/app/postgres.go:73 +0xd7
main.start.func1()
	/app/main.go:63 +0x45
created by main.start in goroutine 1
	/app/main.go:62 +0x1c5
```

**Expected behavior**
Expected ERROR to be shown or sql query to be successfully executed

Best regards,
Artyom Zarubin
Postgres Professional: https://postgrespro.com/

**Comment by exAspArk** [comment]
Hi @Gudwlin — thank you for submitting this issue!

If you download the [latest version](https://github.com/BemiHQ/BemiDB#quickstart), this query shouldn't crash with the runtime error anymore, and instead it should return this:

```
> psql postgres://localhost:54321/bemidb -c "SELECT * FROM test('val')" 
Catalog Error: Table Function with name test does not exist!
Did you mean "test_all_types"?
LINE 1: SELECT * FROM test('val')
                      ^
```

As for custom user-defined functions, those are not supported. We might add support for them, but not in the near future, as we're prioritizing what's on our current [roadmap](https://github.com/BemiHQ/BemiDB#future-roadmap) first.

Please feel free to share your thoughts and comments!
