### ISSUE TITLE
Server crashes when executing SELECT 1::int2 FROM (VALUES (1)) t(x);

### ISSUE THREAD

**Issue by Gudwlin** [BemiHQ/BemiDB#31]
**Describe the bug**
Server crashes when executing the following psql command

**What data setup do we need to do?**
BemiDB(main) with PostgreSQL (REL_17_STABLE).

**What is the necessary configuration info needed?**
My PostgreSQL configuration:
```
./configure
```

**What is the command that caused the error?**
```
psql postgres://localhost:54321/bemidb -c "SELECT 1::int2 FROM (VALUES (1)) t(x);"
```

backtrace:
```
panic: Unsupported queried type: int16

goroutine 8 [running]:
main.(*QueryHandler).generateDataRow(0xc000667ae0?, 0xc000667ae0, {0xc0005ec938, 0x1, 0x2bd4200?})
	/app/query_handler.go:458 +0x1b25
main.(*QueryHandler).rowsToDataMessages(0xc000113a60, 0xc000667ae0, {0xc0000461e0, 0x25})
	/app/query_handler.go:355 +0x18f
main.(*QueryHandler).HandleQuery(0xc000113a60, {0xc000046150, 0x26})
	/app/query_handler.go:201 +0x3cf
main.(*Postgres).handleSimpleQuery(0xc00013c2b8, 0xc000113a60, 0xc0000c2b00)
	/app/postgres.go:95 +0xb6
main.(*Postgres).Run(0xc00013c2b8, 0xc000113a60)
	/app/postgres.go:73 +0xd7
main.start.func1()
	/app/main.go:63 +0x45
created by main.start in goroutine 1
	/app/main.go:62 +0x1c5
```

**Expected behavior**
Expected ERROR to be shown or sql query to be successfully executed

Best regards,
Artyom Zarubin
Postgres Professional: https://postgrespro.com/

**Comment by exAspArk** [comment]
Hi @Gudwlin — thank you for submitting this issue and catching this bug! We've fixed parsing `int2` values in v0.28.4. Would you be able to download the [latest version](https://github.com/BemiHQ/BemiDB#quickstart) and try again?
