### ISSUE TITLE
Support custom S3-compatible endpoint

### ISSUE THREAD

**Issue by bnol** [BemiHQ/BemiDB#4]
Support custom S3-compatible endpoint such as min.io

**Comment by exAspArk** [comment]
Hey @bnol — thanks for submitting this issue!

I've never used min.io, but because it is S3-compatible, it might just work with BemiDB out of the box. 

I'm not sure how authentication and authorization works. If it is compatible with AWS S3 SDKs, would you be able to try something like this:

```
bemidb \
  --storage-type AWS_S3 \
  --iceberg-path iceberg \
  --aws-region us-east-1 \ # hardcoded https://github.com/minio/minio/discussions/15063
  --aws-s3-bucket [YOUR_BUCKET] \
  --aws-access-key-id [MINIO_ROOT_USER] \
  --aws-secret-access-key [MINIO_ROOT_PASSWORD] \
  start
```

**Comment by renatocron** [comment]
It's necessary to configure the endpoint as well, not just the region, because the SDK will point to the AWS endpoints.


it would be something like this:

```go
// Add these fields to your Config struct
type Config struct {
    Aws struct {
        AccessKeyId     string
        SecretAccessKey string
        Region         string
        S3Bucket       string
        Endpoint       string  // New field for custom endpoint
        ForcePathStyle bool    // New field for path style addressing
    }
    // ... other existing fields
}

func NewS3Storage(config *Config) *StorageS3 {
    awsCredentials := credentials.NewStaticCredentialsProvider(
        config.Aws.AccessKeyId,
        config.Aws.SecretAccessKey,
        "",
    )

    var logMode aws.ClientLogMode
    // if config.LogLevel == LOG_LEVEL_DEBUG {
    //     logMode = aws.LogRequest | aws.LogResponse
    // }

    // Create custom endpoint resolver if endpoint is specified
    var endpointResolver aws.EndpointResolverWithOptions
    if config.Aws.Endpoint != "" {
        endpointResolver = aws.EndpointResolverWithOptionsFunc(func(service, region string, options ...interface{}) (aws.Endpoint, error) {
            return aws.Endpoint{
                URL:               config.Aws.Endpoint,
                SigningRegion:     config.Aws.Region,
                HostnameImmutable: true,
            }, nil
        })
    }

    // Load AWS config with custom options
    configOptions := []func(*awsConfig.LoadOptions) error{
        awsConfig.WithRegion(config.Aws.Region),
        awsConfig.WithCredentialsProvider(awsCredentials),
        awsConfig.WithClientLogMode(logMode),
    }

    // Add custom endpoint resolver if specified
    if endpointResolver != nil {
        configOptions = append(configOptions, 
            awsConfig.WithEndpointResolverWithOptions(endpointResolver))
    }

    // Add force path style option if specified
    if config.Aws.ForcePathStyle {
        configOptions = append(configOptions,
            awsConfig.WithS3ForcePathStyle(true))
    }

    loadedAwsConfig, err := awsConfig.LoadDefaultConfig(
        context.Background(),
        configOptions...,
    )
    PanicIfError(err)

    return &StorageS3{
        s3Client:    s3.NewFromConfig(loadedAwsConfig),
        config:      config,
        storageBase: &StorageBase{config: config},
    }
}
```

**Comment by bnol** [comment]
@renatocron perhaps you should submit a PR? :D

**Comment by exAspArk** [comment]
Ah, you're right, good point!

---

We, unfortunately, won't be able to prioritize it in the coming days because we'll be building some of the things mentioned in our [Future Roadmap](https://github.com/BemiHQ/BemiDB#future-roadmap) first (e.g., native support for complex data structures like JSON and arrays)

But if anyone would like to submit a PR, we'll be very happy to help get it merged. At a high level, here are the main things that would need to be updated:

* Add support for a new argument like `--aws-s3-bucket` similarly to other arguments (see `config.go`)
* Write: Pass a custom endpoint as `BaseEndpoint` into `NewFromConfig` when creating an S3 client ([AWS SDK Go V2](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws#Config))
* Read: Add `ENDPOINT` into the DuckDB's secret to be able to read Iceberg tables (see `aws_s3_secret`)

**Comment by exAspArk** [comment]
We've added support for custom S3-compatible endpoints by using the `--aws-s3-endpoint` CLI argument in the latest v0.22.0. More details in the [Configuration options](https://github.com/BemiHQ/BemiDB#configuration-options) section.

Would you be able to download the [latest version](https://github.com/BemiHQ/BemiDB#quickstart) and try it? Let us know if you have any questions!
