### ISSUE TITLE
Support Google Clod Storage

### ISSUE THREAD

**Issue by yu-iskw** [BemiHQ/BemiDB#7]
It would be great to support GCS in addition to S3. That would be very beneficial for many Google Cloud users.

**Comment by yu-iskw** [comment]
@exAspArk Thank you for the suggestion. I didn't know that feature. I will try it out.

**Comment by exAspArk** [comment]
> I suspect it'll be necessary to customize an S3 endpoint

Sorry, just to clarify, ^ this part is not implemented yet.

But I'm going to close this issue in favor of a generic S3 endpoint customization #4
